-- Seed file for local development
-- Note: Test users must be created via Supabase Auth API, not via SQL
-- Use scripts/create_admin.mjs or scripts/create_test_users.mjs after migration
-- All test users use password: password123
