-- Seed file for local development
--
-- Users are created automatically via 'npm run db:seed-users'
-- which runs after 'npm run db:reset'
--
-- For production: npm run db:seed-users:prod
--
-- Add any SQL seed data here (not users - managed via Auth API)
