#!/usr/bin/env python3
"""
Генератор seed.sql для автоматической загрузки данных после db reset.

Создает SQL файл с 100 recognitions + images + annotations для быстрой разработки.
Supabase автоматически применяет seed.sql после каждого db reset.

Usage:
    python3 scripts/generate_seed.py
"""

import json
import sys
from pathlib import Path
from datetime import datetime

def load_config():
    """Загружает конфигурацию."""
    config_file = Path(__file__).parent / "db_config.json"
    with open(config_file, 'r') as f:
        return json.load(f)

def escape_sql_string(s):
    """Экранирует строку для SQL."""
    if s is None:
        return 'NULL'
    s = str(s).replace("'", "''").replace('\\', '\\\\')
    return f"'{s}'"

def main():
    print("=" * 70)
    print("GENERATING seed.sql")
    print("=" * 70)
    print()
    
    config = load_config()
    qwen_json_path = Path(config['dataset_paths']['default_qwen_json'])
    
    if not qwen_json_path.exists():
        print(f"❌ QWEN annotations not found: {qwen_json_path}")
        sys.exit(1)
    
    print(f"📄 Loading: {qwen_json_path.name}")
    
    # Загружаем QWEN annotations
    with open(qwen_json_path, 'r', encoding='utf-8') as f:
        qwen_data = json.load(f)
    
    print(f"✅ Loaded {len(qwen_data)} QWEN entries")
    
    # Берем первые 100
    limit = 100
    recognitions = qwen_data[:limit]
    
    print(f"✅ Selected {len(recognitions)} recognitions for seed")
    
    # Подсчитываем images и annotations
    total_images = sum(len(rec.get('images', [])) for rec in recognitions)
    total_annotations = sum(
        len(img.get('annotations', [])) 
        for rec in recognitions 
        for img in rec.get('images', [])
    )
    
    print(f"✅ Total images: {total_images}")
    print(f"✅ Total annotations: {total_annotations}")
    print()
    
    # Генерируем SQL
    print("📝 Generating SQL...")
    
    sql_lines = []
    sql_lines.append("-- Seed data for local development")
    sql_lines.append("-- Auto-generated by scripts/generate_seed.py")
    sql_lines.append(f"-- Generated: {datetime.now().isoformat()}")
    sql_lines.append(f"-- Contains: {len(recognitions)} recognitions, {total_images} images, {total_annotations} annotations")
    sql_lines.append("")
    
    # Получаем ID dish_validation stage
    sql_lines.append("-- Get dish_validation stage_id")
    sql_lines.append("DO $$")
    sql_lines.append("DECLARE")
    sql_lines.append("  v_stage_id INTEGER;")
    sql_lines.append("BEGIN")
    sql_lines.append("  SELECT ws.id INTO v_stage_id")
    sql_lines.append("  FROM workflow_stages ws")
    sql_lines.append("  JOIN task_types tt ON ws.task_type_id = tt.id")
    sql_lines.append("  WHERE tt.code = 'dish_validation'")
    sql_lines.append("  LIMIT 1;")
    sql_lines.append("")
    
    # Recognitions
    sql_lines.append("  -- Insert recognitions")
    for rec in recognitions:
        recognition_id = rec.get('recognition_id')
        recognition_date = rec.get('RecognitionDate', '')
        correct_dishes = rec.get('CorrectDishes', [])
        menu_all = rec.get('MenuAllExtended', [])
        
        correct_dishes_json = json.dumps(correct_dishes).replace("'", "''")
        menu_all_json = json.dumps(menu_all).replace("'", "''")
        
        sql_lines.append(f"  INSERT INTO recognitions (recognition_id, recognition_date, status, has_modifications, is_mistake, correct_dishes, menu_all, workflow_state, current_stage_id, has_check_error)")
        sql_lines.append(f"  VALUES ({recognition_id}, {escape_sql_string(recognition_date)}, 'not_started', FALSE, FALSE, '{correct_dishes_json}'::jsonb, '{menu_all_json}'::jsonb, 'pending', v_stage_id, FALSE)")
        sql_lines.append(f"  ON CONFLICT (recognition_id) DO NOTHING;")
        sql_lines.append("")
    
    # Images и Annotations
    image_id = 1
    annotation_id = 1
    
    sql_lines.append("  -- Insert images and annotations")
    
    for rec in recognitions:
        recognition_id = rec.get('recognition_id')
        recognition_date = rec.get('RecognitionDate', '')
        
        for img in rec.get('images', []):
            photo_type = img.get('photo_type')
            storage_path = f"recognition_{recognition_id}/recognition_{recognition_id}_{recognition_date}_{photo_type}.jpg"
            
            # Insert image
            sql_lines.append(f"  INSERT INTO recognition_images (id, recognition_id, photo_type, storage_path)")
            sql_lines.append(f"  VALUES ({image_id}, {recognition_id}, {escape_sql_string(photo_type)}, {escape_sql_string(storage_path)})")
            sql_lines.append(f"  ON CONFLICT (id) DO NOTHING;")
            sql_lines.append("")
            
            # Insert annotations для этого image
            for ann in img.get('annotations', []):
                bbox = ann.get('bbox', {})
                x1 = bbox.get('x1', 0)
                y1 = bbox.get('y1', 0)
                x2 = bbox.get('x2', 0)
                y2 = bbox.get('y2', 0)
                
                object_type = ann.get('object_type', 'food')
                dish_index = ann.get('dish_index')
                dish_code = ann.get('dish_code', '')
                is_error = ann.get('is_error', False)
                
                sql_lines.append(f"  INSERT INTO annotations (id, image_id, x1, y1, x2, y2, object_type, dish_index, dish_code, is_error)")
                sql_lines.append(f"  VALUES ({annotation_id}, {image_id}, {x1}, {y1}, {x2}, {y2}, {escape_sql_string(object_type)}, {dish_index if dish_index is not None else 'NULL'}, {escape_sql_string(dish_code)}, {is_error})")
                sql_lines.append(f"  ON CONFLICT (id) DO NOTHING;")
                sql_lines.append("")
                
                annotation_id += 1
            
            image_id += 1
    
    sql_lines.append("  RAISE NOTICE 'Seed data loaded: % recognitions, % images, % annotations', ")
    sql_lines.append(f"    {len(recognitions)}, {total_images}, {total_annotations};")
    sql_lines.append("END $$;")
    
    # Записываем в файл
    output_file = Path(__file__).parent.parent / 'supabase' / 'seed.sql'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"✅ Generated: {output_file}")
    print()
    print("=" * 70)
    print("✅ SEED.SQL GENERATED SUCCESSFULLY!")
    print("=" * 70)
    print()
    print(f"File: {output_file}")
    print(f"Size: {output_file.stat().st_size / 1024:.1f} KB")
    print()
    print("After 'npx supabase db reset --local', seed.sql will be applied automatically")
    print()

if __name__ == '__main__':
    main()
